[build]
command = "npm run build"
publish = ".next" # Or "out" for static export

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://alpha.limo/*"
  to = "https://www.alpha.limo/:splat"
  status = 301
  force = true